# -*- coding: utf-8 -*-
"""Animal Python Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUDo2_b_k14w7HpSvQ-KPDErhE1K0CPw
"""

import numpy as np

import pandas as pd

import requests

from bs4 import BeautifulSoup

# Animal website for generating web scraping

linkk ="https://geographyscout.com/animals/wild-animals-of-india/"

reque = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}
data = requests.get(linkk,headers=reque)
data

data.content

tt=BeautifulSoup(data.text,"html.parser")
tt

tt.find_all("a",href="https://geographyscout.com/animals/interesting-facts-about-tigers/")

rr  = []
for i in tt.find_all("h3"):
    rr.append(i.text)

rr

gg = rr[0:10]
gg

hh  = []
for i in tt.find_all("p"):
    hh.append(i.text)

hh

family =[item for item in hh if item.startswith('Family:')]
family

family1 =[item.replace('Family:', '').strip() for item in family]
family1

population=[item for item in hh if item.startswith("Total Population:")]
population

population1=[kk.replace('Total Population:',"").strip() for kk in population]
population1

kingdom=[item for item in hh if item.startswith("Kingdom:")]
kingdom

Kingdom1=[item.replace("Kingdom:","").strip() for item in kingdom]
Kingdom1

Average=[item for item in hh if item.startswith("Average life:")]
Average

Average1=[item.replace("Average life:",'').split() for item in Average ]
Average1

Average2 = []
for item in Average1:
    Average2.append("".join(item))

Average2

table = pd.DataFrame({"Animal_name":gg,"Family":family1,"Total_population":population1,"Kingdom":Kingdom1,"Average_life":Average2})
table

table.to_csv("shared_table.csv",index=False)

#All Details for Animal table

pip install ydata-profiling

from ydata_profiling import ProfileReport

rr = ProfileReport(table)
rr